[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
# Optimizations for CI
fuzz_runs = 5
# Add any other CI-specific optimizations

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "foundry-devops/=lib/foundry-devops/src/",
  "forge-std/=lib/forge-std/src/"
]

fs_permissions = [
  { access = "read-write", path = "./broadcast" },
  { access = "read-write", path = "./escrows.json" }
]