[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Add fs_permissions under the profile
fs_permissions = [
  { access = "read-write", path = "./broadcast" },
  { access = "read-write", path = "./escrows.json" }
]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
fuzz_runs = 5
# Also add fs_permissions for CI profile
fs_permissions = [
  { access = "read-write", path = "./broadcast" },
  { access = "read-write", path = "./escrows.json" }
]

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "foundry-devops/=lib/foundry-devops/", 
  "forge-std/=lib/forge-std/src/"
]